# Generated by Django 2.2.3 on 2019-08-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_app', '0006_auto_20190813_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(blank=True, upload_to='profile'),
        ),
    ]
